package getter

import (
	"encoding/json"
	"fmt"
	"io"
	"os"
)

func RunData() ([]byte, error) {

	jsonFile, err := os.Open("model.json")
	if err != nil {
		return nil, err
	}
	fmt.Println("Successfully Opened model.json")
	defer jsonFile.Close()

	byteValue, err := io.ReadAll(jsonFile)
	if err != nil {
		return nil, err
	}
	return byteValue, nil
}
func Under(t []byte) (AutoGenerated, error) {
	var table AutoGenerated
	err := json.Unmarshal(t, &table)
	if err != nil {
		return AutoGenerated{}, err
	}
	return table, nil
}
